### ISSUE TITLE
Can't open a single link on the site

### ISSUE THREAD

**Issue by sophiataskova** [Abstrct/Schemaverse#37]
Every link I click on opens the registration form; when I register, nothing happens and I'm still looking at the blank form. Am I doing something wrong? I tried both https://schemaverse.com/tutorial/tutorial.php and https://schemaverse.com/tw/index.php

**Comment by egodin** [comment]
Same here, I think the site may not be maintained and in any case there was no ongoing game for a while (checking regularly).

**Comment by GuillaumeRossolini** [comment]
Firefox says: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by Abstrct** [comment]
Fixed, just switched over to Lets Encrypt. Site seems to be working now.
